version: '3.8'

services:

  postgres:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - analyzer_network

networks:
  analyzer_network:
    driver: bridge