version: '3.8'

services:

  gateway:
    image: traefik:v2.2.1
    ports:
      - "5080:80" # Port of the API Gateway, which will be the port behind which the system will be published
      - "5088:8080" # Dashboard of Traefik for troubleshooting
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - analyzer_network
  
  auth:
    build: auth
    environment: 
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on: 
      - postgres
      - text_analyzer_es
    networks:
      - analyzer_network

  profanityfilter:
    build: nlp-services/profanityfilter
    depends_on: 
      - auth
      - gateway
    networks:
      - analyzer_network

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=textanalyzer
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - analyzer_network

  text_analyzer_es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: text_analyzer_es
    environment:
      - cluster.name=text-analyzer-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - text_analyzer_es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - analyzer_network
  
  text_analyzer_kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: text_analyzer_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://text_analyzer_es:9200
    depends_on:
      - text_analyzer_es
    ports:
      - 5601:5601
    networks:
      - analyzer_network

volumes:
  text_analyzer_es_data:
    driver: local

networks:
  analyzer_network:
    driver: bridge
