server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "Set-Cookie"
            maxAge: 86400
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

services:
  auth:
    url: ${AUTH_URL}
  executor:
    url: ${EXECUTOR_URL}
jwt:
  secret: 16jZfHALbOhKAzBEKvZO6rVnz7etTLX3af5uAHgLPVI= #${JWT_SECRET}
  accessTokenCookieName: accessToken
