server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000
spring:
  application:
    name: auth
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 3MB

config:
  issuerUrl: http://localhost:9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
